# Generated by Django 4.2.24 on 2025-09-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0002_alter_subscriptions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'code_name__in': ['b', 'b', 'p', 'a'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
