# Generated by Django 4.2.24 on 2025-09-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_subscriptionprice_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='is_active',
            new_name='active',
        ),
    ]
