# Generated by Django 4.2.24 on 2025-09-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_rename_is_active_subscriptions_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='tripe_id',
            new_name='stripe_id',
        ),
    ]
