# Generated by Django 4.2.24 on 2025-09-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_rename_tripe_id_subscriptions_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='interval',
            field=models.CharField(choices=[('Dayly', 'Dayly'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=120),
        ),
    ]
