# Generated by Django 4.2.24 on 2025-09-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_subscriptionprice_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionprice',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='subscriptionprice',
            name='interval',
            field=models.CharField(choices=[('day', 'Dayly'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=120),
        ),
    ]
