# Generated by Django 4.2.24 on 2025-09-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='features',
            field=models.TextField(blank=True, help_text='Features for pricing, seperated by new line', null=True),
        ),
    ]
