# Generated by Django 4.2.24 on 2025-09-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_subscriptions_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Features for pricing, seperated by new line', null=True),
        ),
    ]
