# Generated by Django 4.2.24 on 2025-09-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_subscriptions_subtitle_alter_subscriptions_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='subtitle',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
