# Generated by Django 4.2.24 on 2025-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('day_bir', models.IntegerField(blank=True)),
                ('month_bir', models.IntegerField(blank=True)),
                ('year_bir', models.IntegerField()),
                ('sex', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Nam', max_length=120)),
                ('dan_toc', models.CharField(default='Kinh', max_length=120)),
                ('address', models.TextField(default='Tổ 11 - Đông An')),
                ('so_phieu', models.TextField(default='DA11001')),
                ('dien_cu_tru', models.TextField(default='Thường trú')),
                ('lop_hoc', models.TextField(blank=True)),
                ('truong', models.TextField(blank=True, default=' - Núi Thành')),
                ('bac_tot_nghiep', models.TextField(choices=[('', ''), ('TH', 'TH'), ('THCS', 'THCS'), ('THPT', 'THPT'), ('ĐH', 'ĐH')])),
                ('nam_tot_nghiep', models.IntegerField(blank=True)),
                ('quan_he_voi_chu_ho', models.TextField(choices=[('Chủ hộ', 'Chủ hộ'), ('Chồng', 'Chồng'), ('Vợ', 'Vợ'), ('Con', 'Con'), ('Cháu', 'Cháu'), ('Con dâu', 'Con dâu'), ('Con rễ', 'Con rễ')])),
                ('ten_cha_hoac_me', models.TextField(blank=True)),
                ('sdt', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
