# Generated by Django 4.2.24 on 2025-09-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='day_bir',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='lop_hoc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='information',
            name='month_bir',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='nam_tot_nghiep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='information',
            name='sdt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='information',
            name='ten_cha_hoac_me',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='information',
            name='truong',
            field=models.TextField(blank=True, default=' - Núi Thành', null=True),
        ),
    ]
