# Generated by Django 4.2.24 on 2025-09-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infor', '0002_alter_information_day_bir_alter_information_lop_hoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='bac_tot_nghiep',
            field=models.TextField(blank=True, choices=[(' ', ' '), ('MN', 'MN'), ('TH', 'TH'), ('THCS', 'THCS'), ('THPT', 'THPT'), ('ĐH', 'ĐH')], null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='truong',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
